import { library as IconLibrary } from "@fortawesome/fontawesome-svg-core"

import { faCheckCircle, faMobileAndroid, faGlobe, faClone } from "@fortawesome/pro-regular-svg-icons"
import {
	faUserCircle as falUserCircle,
	faUser as falUser,
	faEnvelope,
	faChevronDown as falChevronDown,
	faChevronUp,
	faChevronRight,
	faSignOut,
	faUserCog,
	faUserTag as falUserTag,
	faBarcode,
	faBarcodeAlt,
	faTimes as falTimes,
	faPlusCircle,
	faContainerStorage,
	faPalletAlt as falPalletAlt,
	faSteak as falSteak,
	faBox as falBox,
	faPencil,
	faSmile as falSmile,
	faStar as falStar,
	faQrcode,
	faFileContract as falFileContract,
	faFolderTree,
	faFile as falFile,
	faShoppingBasket as falShoppingBasket,
} from "@fortawesome/pro-light-svg-icons"
import {
	faUserCircle,
	faHeadset,
	faHandHoldingBox,
	faUser,
	faMoneyCheckAlt,
	faChartPie,
	faUsers,
	faEdit,
	faUserTag,
	faCogs,
	faSearch,
	faFilter,
	faCheck,
	faTimes,
	faLink,
	faTrash,
	faInfoCircle,
	faInventory,
	faShoppingCart,
	faBox,
	faPalletAlt,
	faArchive,
	faUndo,
	faSave,
	faSteak,
	faFileExcel,
	faSmile,
	faStar,
	faTruckMoving,
	faFileContract,
	faUserChart,
	faChartLine,
	faCubes,
	faFile,
	faExternalLink,
	faFileDownload,
	faShoppingBasket,
	faChevronDown,
	faChevronLeft as fasChevronLeft,
	faChevronRight as fasChevronRight,
} from "@fortawesome/pro-solid-svg-icons"

export const loadIcons = () => {
	IconLibrary.add(
		faHeadset,
		faHandHoldingBox,
		faUser,
		falUser,
		faMoneyCheckAlt,
		faUserCircle,
		falUserCircle,
		faEnvelope,
		faChevronDown,
		falChevronDown,
		faChevronUp,
		faChevronRight,
		faSignOut,
		faUserCog,
		faChartPie,
		faUsers,
		faEdit,
		faUserTag,
		falUserTag,
		faCogs,
		faBarcode,
		faBarcodeAlt,
		faSearch,
		faFilter,
		faCheck,
		faTimes,
		falTimes,
		faLink,
		faTrash,
		faInfoCircle,
		faPlusCircle,
		faInventory,
		faContainerStorage,
		faPalletAlt,
		falPalletAlt,
		faBox,
		falBox,
		faSteak,
		falSteak,
		faPencil,
		faShoppingCart,
		faArchive,
		faUndo,
		faSave,
		faFileExcel,
		faCheckCircle,
		faMobileAndroid,
		faGlobe,
		faSmile,
		falSmile,
		faStar,
		falStar,
		faQrcode,
		faTruckMoving,
		faFileContract,
		falFileContract,
		faClone,
		faFolderTree,
		faUserChart,
		faChartLine,
		faCubes,
		faFile,
		falFile,
		faExternalLink,
		faFileDownload,
		faShoppingBasket,
		falShoppingBasket,
		fasChevronLeft,
		fasChevronRight,
	)
}
