#!/bin/bash
set -e
source /var/scripts/set-genesis-env.sh

echo "Pulling container..."

echo $DOCKER_TOKEN | docker login docker.pkg.github.com -u nii236 --password-stdin &> /dev/null
docker pull --quiet  docker.pkg.github.com/ninja-software/genesis/genesis:latest &> /dev/null

echo "Removing existing containers..."

[ "$(docker ps -a | grep genesis)" ] && docker stop genesis &> /dev/null
[ "$(docker ps -a | grep genesis)" ] && docker rm genesis &> /dev/null

echo "Dropping database..."

docker run \
        --rm \
        --name genesis-db-client \
        -e GENESIS_API_ADDR="$GENESIS_API_ADDR" \
        -e GENESIS_API_BLOBBASEURL="$GENESIS_API_BLOBBASEURL" \
        -e GENESIS_LOADBALANCER_ADMINADDR="$GENESIS_LOADBALANCER_ADMINADDR" \
        -e GENESIS_LOADBALANCER_ADMINROOTPATH="$GENESIS_LOADBALANCER_ADMINROOTPATH" \
        -e GENESIS_LOADBALANCER_ADMININDEXFILE="$GENESIS_LOADBALANCER_ADMININDEXFILE" \
        -e GENESIS_LOADBALANCER_CONSUMERADDR="$GENESIS_LOADBALANCER_CONSUMERADDR" \
        -e GENESIS_LOADBALANCER_CONSUMERROOTPATH="$GENESIS_LOADBALANCER_CONSUMERROOTPATH" \
        -e GENESIS_LOADBALANCER_CONSUMERINDEXFILE="$GENESIS_LOADBALANCER_CONSUMERINDEXFILE" \
        -e GENESIS_USERAUTH_JWTSECRET="$GENESIS_USERAUTH_JWTSECRET" \
        -e GENESIS_USERAUTH_TOKENEXPIRYDAYS="$GENESIS_USERAUTH_TOKENEXPIRYDAYS" \
        -e GENESIS_USERAUTH_RESETTOKENEXPIRYDAYS="$GENESIS_USERAUTH_RESETTOKENEXPIRYDAYS" \
        -e GENESIS_USERAUTH_BLACKLISTREFRESHHOURS="$GENESIS_USERAUTH_BLACKLISTREFRESHHOURS" \
        -e GENESIS_EMAIL_DOMAIN="$GENESIS_EMAIL_DOMAIN" \
        -e GENESIS_EMAIL_SENDER="$GENESIS_EMAIL_SENDER" \
        -e GENESIS_EMAIL_APIKEY="$GENESIS_EMAIL_APIKEY" \
        -e GENESIS_DATABASE_USER="$GENESIS_DATABASE_USER" \
        -e GENESIS_DATABASE_PASS="$GENESIS_DATABASE_PASS" \
        -e GENESIS_DATABASE_HOST="$(ip -4 addr show docker0 | grep -Po 'inet \K[\d.]+')" \
        -e GENESIS_DATABASE_PORT="$GENESIS_DATABASE_PORT" \
        -e GENESIS_DATABASE_NAME="$GENESIS_DATABASE_NAME" \
        -e GENESIS_SKIP_USERVERIFICATION="$GENESIS_SKIP_USERVERIFICATION" \
        -e GENESIS_SENTRY_DSN="$GENESIS_SENTRY_DSN" \
        -e GENESIS_SENTRY_SERVERNAME="$GENESIS_SENTRY_SERVERNAME" \
        -e GENESIS_SENTRY_ENVIRONMENT="$GENESIS_SENTRY_ENVIRONMENT" \
docker.pkg.github.com/ninja-software/genesis/genesis:latest /main db --db_drop

echo "Migrating database..."

docker run \
        --rm \
        --name genesis-db-client \
        -e GENESIS_API_ADDR="$GENESIS_API_ADDR" \
        -e GENESIS_API_BLOBBASEURL="$GENESIS_API_BLOBBASEURL" \
        -e GENESIS_LOADBALANCER_ADMINADDR="$GENESIS_LOADBALANCER_ADMINADDR" \
        -e GENESIS_LOADBALANCER_ADMINROOTPATH="$GENESIS_LOADBALANCER_ADMINROOTPATH" \
        -e GENESIS_LOADBALANCER_ADMININDEXFILE="$GENESIS_LOADBALANCER_ADMININDEXFILE" \
        -e GENESIS_LOADBALANCER_CONSUMERADDR="$GENESIS_LOADBALANCER_CONSUMERADDR" \
        -e GENESIS_LOADBALANCER_CONSUMERROOTPATH="$GENESIS_LOADBALANCER_CONSUMERROOTPATH" \
        -e GENESIS_LOADBALANCER_CONSUMERINDEXFILE="$GENESIS_LOADBALANCER_CONSUMERINDEXFILE" \
        -e GENESIS_USERAUTH_JWTSECRET="$GENESIS_USERAUTH_JWTSECRET" \
        -e GENESIS_USERAUTH_TOKENEXPIRYDAYS="$GENESIS_USERAUTH_TOKENEXPIRYDAYS" \
        -e GENESIS_USERAUTH_RESETTOKENEXPIRYDAYS="$GENESIS_USERAUTH_RESETTOKENEXPIRYDAYS" \
        -e GENESIS_USERAUTH_BLACKLISTREFRESHHOURS="$GENESIS_USERAUTH_BLACKLISTREFRESHHOURS" \
        -e GENESIS_EMAIL_DOMAIN="$GENESIS_EMAIL_DOMAIN" \
        -e GENESIS_EMAIL_SENDER="$GENESIS_EMAIL_SENDER" \
        -e GENESIS_EMAIL_APIKEY="$GENESIS_EMAIL_APIKEY" \
        -e GENESIS_DATABASE_USER="$GENESIS_DATABASE_USER" \
        -e GENESIS_DATABASE_PASS="$GENESIS_DATABASE_PASS" \
        -e GENESIS_DATABASE_HOST="$(ip -4 addr show docker0 | grep -Po 'inet \K[\d.]+')" \
        -e GENESIS_DATABASE_PORT="$GENESIS_DATABASE_PORT" \
        -e GENESIS_DATABASE_NAME="$GENESIS_DATABASE_NAME" \
        -e GENESIS_SKIP_USERVERIFICATION="$GENESIS_SKIP_USERVERIFICATION" \
        -e GENESIS_SENTRY_DSN="$GENESIS_SENTRY_DSN" \
        -e GENESIS_SENTRY_SERVERNAME="$GENESIS_SENTRY_SERVERNAME" \
        -e GENESIS_SENTRY_ENVIRONMENT="$GENESIS_SENTRY_ENVIRONMENT" \
docker.pkg.github.com/ninja-software/genesis/genesis:latest /main db --db_migrate

echo "Seeding database..."

docker run \
        --rm \
        --name genesis-db-client \
        -e GENESIS_API_ADDR="$GENESIS_API_ADDR" \
        -e GENESIS_API_BLOBBASEURL="$GENESIS_API_BLOBBASEURL" \
        -e GENESIS_LOADBALANCER_ADMINADDR="$GENESIS_LOADBALANCER_ADMINADDR" \
        -e GENESIS_LOADBALANCER_ADMINROOTPATH="$GENESIS_LOADBALANCER_ADMINROOTPATH" \
        -e GENESIS_LOADBALANCER_ADMININDEXFILE="$GENESIS_LOADBALANCER_ADMININDEXFILE" \
        -e GENESIS_LOADBALANCER_CONSUMERADDR="$GENESIS_LOADBALANCER_CONSUMERADDR" \
        -e GENESIS_LOADBALANCER_CONSUMERROOTPATH="$GENESIS_LOADBALANCER_CONSUMERROOTPATH" \
        -e GENESIS_LOADBALANCER_CONSUMERINDEXFILE="$GENESIS_LOADBALANCER_CONSUMERINDEXFILE" \
        -e GENESIS_USERAUTH_JWTSECRET="$GENESIS_USERAUTH_JWTSECRET" \
        -e GENESIS_USERAUTH_TOKENEXPIRYDAYS="$GENESIS_USERAUTH_TOKENEXPIRYDAYS" \
        -e GENESIS_USERAUTH_RESETTOKENEXPIRYDAYS="$GENESIS_USERAUTH_RESETTOKENEXPIRYDAYS" \
        -e GENESIS_USERAUTH_BLACKLISTREFRESHHOURS="$GENESIS_USERAUTH_BLACKLISTREFRESHHOURS" \
        -e GENESIS_EMAIL_DOMAIN="$GENESIS_EMAIL_DOMAIN" \
        -e GENESIS_EMAIL_SENDER="$GENESIS_EMAIL_SENDER" \
        -e GENESIS_EMAIL_APIKEY="$GENESIS_EMAIL_APIKEY" \
        -e GENESIS_DATABASE_USER="$GENESIS_DATABASE_USER" \
        -e GENESIS_DATABASE_PASS="$GENESIS_DATABASE_PASS" \
        -e GENESIS_DATABASE_HOST="$(ip -4 addr show docker0 | grep -Po 'inet \K[\d.]+')" \
        -e GENESIS_DATABASE_PORT="$GENESIS_DATABASE_PORT" \
        -e GENESIS_DATABASE_NAME="$GENESIS_DATABASE_NAME" \
        -e GENESIS_SKIP_USERVERIFICATION="$GENESIS_SKIP_USERVERIFICATION" \
        -e GENESIS_SENTRY_DSN="$GENESIS_SENTRY_DSN" \
        -e GENESIS_SENTRY_SERVERNAME="$GENESIS_SENTRY_SERVERNAME" \
        -e GENESIS_SENTRY_ENVIRONMENT="$GENESIS_SENTRY_ENVIRONMENT" \
docker.pkg.github.com/ninja-software/genesis/genesis:latest /main db --db_seed


docker run \
        --detach \
        --name genesis \
        -p 8086:8080 \
        -p 8088:8082 \
        -v /var/scripts/genesis-key:/keys/UTC--2020-04-06T06-20-59.480007797Z--a7a2e5c7eb9f79b75af6ce6e0ad64e6e61d116ea \
        -e GENESIS_API_ADDR="$GENESIS_API_ADDR" \
        -e GENESIS_API_BLOBBASEURL="$GENESIS_API_BLOBBASEURL" \
        -e GENESIS_API_CONSUMERHOST="$GENESIS_API_CONSUMERHOST" \
        -e GENESIS_API_ADMINHOST="$GENESIS_API_ADMINHOST" \
        -e GENESIS_BLOCKCHAIN_ETHEREUMHOST="http://$(ip -4 addr show docker0 | grep -Po 'inet \K[\d.]+'):8545" \
        -e GENESIS_BLOCKCHAIN_ETHERSCANHOST="$GENESIS_BLOCKCHAIN_ETHERSCANHOST" \
        -e GENESIS_BLOCKCHAIN_PRIVATEKEYFILE="$GENESIS_BLOCKCHAIN_PRIVATEKEYFILE" \
        -e GENESIS_BLOCKCHAIN_PRIVATEKEYPASSWORD="$GENESIS_BLOCKCHAIN_PRIVATEKEYPASSWORD" \
        -e GENESIS_BLOCKCHAIN_TESTPRIVATEKEY="$GENESIS_BLOCKCHAIN_TESTPRIVATEKEY" \
        -e GENESIS_BLOCKCHAIN_CREATECONTRACTONFIRSTRUN="$GENESIS_BLOCKCHAIN_CREATECONTRACTONFIRSTRUN" \
        -e GENESIS_BLOCKCHAIN_FLUSHPENDINGINTERVAL="$GENESIS_BLOCKCHAIN_FLUSHPENDINGINTERVAL" \
        -e BLOCKCHAIN_ETH_LOW_NOTIFY_AMOUNT="$BLOCKCHAIN_ETH_LOW_NOTIFY_AMOUNT" \
        -e BLOCKCHAIN_ETH_LOW_NOTIFY_EMAIL="$BLOCKCHAIN_ETH_LOW_NOTIFY_EMAIL" \
        -e GENESIS_FIELDAPP_VERSION="$GENESIS_FIELDAPP_VERSION" \
        -e GENESIS_DATABASE_HOST="$(ip -4 addr show docker0 | grep -Po 'inet \K[\d.]+')" \
        -e GENESIS_DATABASE_NAME="$GENESIS_DATABASE_NAME" \
        -e GENESIS_DATABASE_PASS="$GENESIS_DATABASE_PASS" \
        -e GENESIS_DATABASE_PORT="$GENESIS_DATABASE_PORT" \
        -e GENESIS_DATABASE_USER="$GENESIS_DATABASE_USER" \
        -e GENESIS_EMAIL_APIKEY="$GENESIS_EMAIL_APIKEY" \
        -e GENESIS_EMAIL_DOMAIN="$GENESIS_EMAIL_DOMAIN" \
        -e GENESIS_EMAIL_SENDER="$GENESIS_EMAIL_SENDER" \
        -e GENESIS_LOADBALANCER_ADMINADDR="$GENESIS_LOADBALANCER_ADMINADDR" \
        -e GENESIS_LOADBALANCER_ADMININDEXFILE="$GENESIS_LOADBALANCER_ADMININDEXFILE" \
        -e GENESIS_LOADBALANCER_ADMINROOTPATH="$GENESIS_LOADBALANCER_ADMINROOTPATH" \
        -e GENESIS_LOADBALANCER_CONSUMERADDR="$GENESIS_LOADBALANCER_CONSUMERADDR" \
        -e GENESIS_LOADBALANCER_CONSUMERINDEXFILE="$GENESIS_LOADBALANCER_CONSUMERINDEXFILE" \
        -e GENESIS_LOADBALANCER_CONSUMERROOTPATH="$GENESIS_LOADBALANCER_CONSUMERROOTPATH" \
        -e GENESIS_SKIP_USERVERIFICATION="$GENESIS_SKIP_USERVERIFICATION" \
        -e GENESIS_SENTRY_DSN="$GENESIS_SENTRY_DSN" \
        -e GENESIS_SENTRY_SERVERNAME="$GENESIS_SENTRY_SERVERNAME" \
        -e GENESIS_SENTRY_ENVIRONMENT="$GENESIS_SENTRY_ENVIRONMENT" \
        -e GENESIS_SMS_ENABLED="$GENESIS_SMS_ENABLED" \
        -e GENESIS_SMS_SID="$GENESIS_SMS_SID" \
        -e GENESIS_SMS_TOKEN="$GENESIS_SMS_TOKEN" \
        -e GENESIS_USERAUTH_BLACKLISTREFRESHHOURS="$GENESIS_USERAUTH_BLACKLISTREFRESHHOURS" \
        -e GENESIS_USERAUTH_JWTSECRET="$GENESIS_USERAUTH_JWTSECRET" \
        -e GENESIS_USERAUTH_RESETTOKENEXPIRYDAYS="$GENESIS_USERAUTH_RESETTOKENEXPIRYDAYS" \
        -e GENESIS_USERAUTH_TOKENEXPIRYDAYS="$GENESIS_USERAUTH_TOKENEXPIRYDAYS" \
docker.pkg.github.com/ninja-software/genesis/genesis:latest
