// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package db

import (
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// Container is an object representing the database table.
type Container struct {
	ID          string    `db:"id" boil:"id" json:"id" toml:"id" yaml:"id"`
	Code        string    `db:"code" boil:"code" json:"code" toml:"code" yaml:"code"`
	Description string    `db:"description" boil:"description" json:"description" toml:"description" yaml:"description"`
	Archived    bool      `db:"archived" boil:"archived" json:"archived" toml:"archived" yaml:"archived"`
	ArchivedAt  null.Time `db:"archived_at" boil:"archived_at" json:"archived_at,omitempty" toml:"archived_at" yaml:"archived_at,omitempty"`
	UpdatedAt   time.Time `db:"updated_at" boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	CreatedAt   time.Time `db:"created_at" boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	CreatedByID string    `db:"created_by_id" boil:"created_by_id" json:"created_by_id" toml:"created_by_id" yaml:"created_by_id"`

	R *containerR `db:"-" boil:"-" json:"-" toml:"-" yaml:"-"`
	L containerL  `db:"-" boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ContainerColumns = struct {
	ID          string
	Code        string
	Description string
	Archived    string
	ArchivedAt  string
	UpdatedAt   string
	CreatedAt   string
	CreatedByID string
}{
	ID:          "id",
	Code:        "code",
	Description: "description",
	Archived:    "archived",
	ArchivedAt:  "archived_at",
	UpdatedAt:   "updated_at",
	CreatedAt:   "created_at",
	CreatedByID: "created_by_id",
}

// Generated where

var ContainerWhere = struct {
	ID          whereHelperstring
	Code        whereHelperstring
	Description whereHelperstring
	Archived    whereHelperbool
	ArchivedAt  whereHelpernull_Time
	UpdatedAt   whereHelpertime_Time
	CreatedAt   whereHelpertime_Time
	CreatedByID whereHelperstring
}{
	ID:          whereHelperstring{field: "\"containers\".\"id\""},
	Code:        whereHelperstring{field: "\"containers\".\"code\""},
	Description: whereHelperstring{field: "\"containers\".\"description\""},
	Archived:    whereHelperbool{field: "\"containers\".\"archived\""},
	ArchivedAt:  whereHelpernull_Time{field: "\"containers\".\"archived_at\""},
	UpdatedAt:   whereHelpertime_Time{field: "\"containers\".\"updated_at\""},
	CreatedAt:   whereHelpertime_Time{field: "\"containers\".\"created_at\""},
	CreatedByID: whereHelperstring{field: "\"containers\".\"created_by_id\""},
}

// ContainerRels is where relationship names are stored.
var ContainerRels = struct {
	CreatedBy string
	Pallets   string
}{
	CreatedBy: "CreatedBy",
	Pallets:   "Pallets",
}

// containerR is where relationships are stored.
type containerR struct {
	CreatedBy *User
	Pallets   PalletSlice
}

// NewStruct creates a new relationship struct
func (*containerR) NewStruct() *containerR {
	return &containerR{}
}

// containerL is where Load methods for each relationship are stored.
type containerL struct{}

var (
	containerAllColumns            = []string{"id", "code", "description", "archived", "archived_at", "updated_at", "created_at", "created_by_id"}
	containerColumnsWithoutDefault = []string{"code", "archived_at", "created_by_id"}
	containerColumnsWithDefault    = []string{"id", "description", "archived", "updated_at", "created_at"}
	containerPrimaryKeyColumns     = []string{"id"}
)

type (
	// ContainerSlice is an alias for a slice of pointers to Container.
	// This should generally be used opposed to []Container.
	ContainerSlice []*Container
	// ContainerHook is the signature for custom Container hook methods
	ContainerHook func(boil.Executor, *Container) error

	containerQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	containerType                 = reflect.TypeOf(&Container{})
	containerMapping              = queries.MakeStructMapping(containerType)
	containerPrimaryKeyMapping, _ = queries.BindMapping(containerType, containerMapping, containerPrimaryKeyColumns)
	containerInsertCacheMut       sync.RWMutex
	containerInsertCache          = make(map[string]insertCache)
	containerUpdateCacheMut       sync.RWMutex
	containerUpdateCache          = make(map[string]updateCache)
	containerUpsertCacheMut       sync.RWMutex
	containerUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var containerBeforeInsertHooks []ContainerHook
var containerBeforeUpdateHooks []ContainerHook
var containerBeforeDeleteHooks []ContainerHook
var containerBeforeUpsertHooks []ContainerHook

var containerAfterInsertHooks []ContainerHook
var containerAfterSelectHooks []ContainerHook
var containerAfterUpdateHooks []ContainerHook
var containerAfterDeleteHooks []ContainerHook
var containerAfterUpsertHooks []ContainerHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Container) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range containerBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Container) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range containerBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Container) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range containerBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Container) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range containerBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Container) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range containerAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Container) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range containerAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Container) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range containerAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Container) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range containerAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Container) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range containerAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddContainerHook registers your hook function for all future operations.
func AddContainerHook(hookPoint boil.HookPoint, containerHook ContainerHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		containerBeforeInsertHooks = append(containerBeforeInsertHooks, containerHook)
	case boil.BeforeUpdateHook:
		containerBeforeUpdateHooks = append(containerBeforeUpdateHooks, containerHook)
	case boil.BeforeDeleteHook:
		containerBeforeDeleteHooks = append(containerBeforeDeleteHooks, containerHook)
	case boil.BeforeUpsertHook:
		containerBeforeUpsertHooks = append(containerBeforeUpsertHooks, containerHook)
	case boil.AfterInsertHook:
		containerAfterInsertHooks = append(containerAfterInsertHooks, containerHook)
	case boil.AfterSelectHook:
		containerAfterSelectHooks = append(containerAfterSelectHooks, containerHook)
	case boil.AfterUpdateHook:
		containerAfterUpdateHooks = append(containerAfterUpdateHooks, containerHook)
	case boil.AfterDeleteHook:
		containerAfterDeleteHooks = append(containerAfterDeleteHooks, containerHook)
	case boil.AfterUpsertHook:
		containerAfterUpsertHooks = append(containerAfterUpsertHooks, containerHook)
	}
}

// One returns a single container record from the query.
func (q containerQuery) One(exec boil.Executor) (*Container, error) {
	o := &Container{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(nil, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "db: failed to execute a one query for containers")
	}

	if err := o.doAfterSelectHooks(exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Container records from the query.
func (q containerQuery) All(exec boil.Executor) (ContainerSlice, error) {
	var o []*Container

	err := q.Bind(nil, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "db: failed to assign all query results to Container slice")
	}

	if len(containerAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Container records in the query.
func (q containerQuery) Count(exec boil.Executor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to count containers rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q containerQuery) Exists(exec boil.Executor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "db: failed to check if containers exists")
	}

	return count > 0, nil
}

// CreatedBy pointed to by the foreign key.
func (o *Container) CreatedBy(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.CreatedByID),
	}

	queryMods = append(queryMods, mods...)

	query := Users(queryMods...)
	queries.SetFrom(query.Query, "\"users\"")

	return query
}

// Pallets retrieves all the pallet's Pallets with an executor.
func (o *Container) Pallets(mods ...qm.QueryMod) palletQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"pallets\".\"container_id\"=?", o.ID),
	)

	query := Pallets(queryMods...)
	queries.SetFrom(query.Query, "\"pallets\"")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"\"pallets\".*"})
	}

	return query
}

// LoadCreatedBy allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (containerL) LoadCreatedBy(e boil.Executor, singular bool, maybeContainer interface{}, mods queries.Applicator) error {
	var slice []*Container
	var object *Container

	if singular {
		object = maybeContainer.(*Container)
	} else {
		slice = *maybeContainer.(*[]*Container)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &containerR{}
		}
		args = append(args, object.CreatedByID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &containerR{}
			}

			for _, a := range args {
				if a == obj.CreatedByID {
					continue Outer
				}
			}

			args = append(args, obj.CreatedByID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(qm.From(`users`), qm.WhereIn(`users.id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.Query(e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(containerAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.CreatedBy = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.CreatedByContainers = append(foreign.R.CreatedByContainers, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.CreatedByID == foreign.ID {
				local.R.CreatedBy = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.CreatedByContainers = append(foreign.R.CreatedByContainers, local)
				break
			}
		}
	}

	return nil
}

// LoadPallets allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (containerL) LoadPallets(e boil.Executor, singular bool, maybeContainer interface{}, mods queries.Applicator) error {
	var slice []*Container
	var object *Container

	if singular {
		object = maybeContainer.(*Container)
	} else {
		slice = *maybeContainer.(*[]*Container)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &containerR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &containerR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.ID) {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(qm.From(`pallets`), qm.WhereIn(`pallets.container_id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.Query(e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load pallets")
	}

	var resultSlice []*Pallet
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice pallets")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on pallets")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for pallets")
	}

	if len(palletAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.Pallets = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &palletR{}
			}
			foreign.R.Container = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.ContainerID) {
				local.R.Pallets = append(local.R.Pallets, foreign)
				if foreign.R == nil {
					foreign.R = &palletR{}
				}
				foreign.R.Container = local
				break
			}
		}
	}

	return nil
}

// SetCreatedBy of the container to the related item.
// Sets o.R.CreatedBy to related.
// Adds o to related.R.CreatedByContainers.
func (o *Container) SetCreatedBy(exec boil.Executor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"containers\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"created_by_id"}),
		strmangle.WhereClause("\"", "\"", 2, containerPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.CreatedByID = related.ID
	if o.R == nil {
		o.R = &containerR{
			CreatedBy: related,
		}
	} else {
		o.R.CreatedBy = related
	}

	if related.R == nil {
		related.R = &userR{
			CreatedByContainers: ContainerSlice{o},
		}
	} else {
		related.R.CreatedByContainers = append(related.R.CreatedByContainers, o)
	}

	return nil
}

// AddPallets adds the given related objects to the existing relationships
// of the container, optionally inserting them as new records.
// Appends related to o.R.Pallets.
// Sets related.R.Container appropriately.
func (o *Container) AddPallets(exec boil.Executor, insert bool, related ...*Pallet) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.ContainerID, o.ID)
			if err = rel.Insert(exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"pallets\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"container_id"}),
				strmangle.WhereClause("\"", "\"", 2, palletPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.DebugMode {
				fmt.Fprintln(boil.DebugWriter, updateQuery)
				fmt.Fprintln(boil.DebugWriter, values)
			}
			if _, err = exec.Exec(updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.ContainerID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &containerR{
			Pallets: related,
		}
	} else {
		o.R.Pallets = append(o.R.Pallets, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &palletR{
				Container: o,
			}
		} else {
			rel.R.Container = o
		}
	}
	return nil
}

// SetPallets removes all previously related items of the
// container replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Container's Pallets accordingly.
// Replaces o.R.Pallets with related.
// Sets related.R.Container's Pallets accordingly.
func (o *Container) SetPallets(exec boil.Executor, insert bool, related ...*Pallet) error {
	query := "update \"pallets\" set \"container_id\" = null where \"container_id\" = $1"
	values := []interface{}{o.ID}
	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, query)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	_, err := exec.Exec(query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.Pallets {
			queries.SetScanner(&rel.ContainerID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.Container = nil
		}

		o.R.Pallets = nil
	}
	return o.AddPallets(exec, insert, related...)
}

// RemovePallets relationships from objects passed in.
// Removes related items from R.Pallets (uses pointer comparison, removal does not keep order)
// Sets related.R.Container.
func (o *Container) RemovePallets(exec boil.Executor, related ...*Pallet) error {
	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.ContainerID, nil)
		if rel.R != nil {
			rel.R.Container = nil
		}
		if _, err = rel.Update(exec, boil.Whitelist("container_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.Pallets {
			if rel != ri {
				continue
			}

			ln := len(o.R.Pallets)
			if ln > 1 && i < ln-1 {
				o.R.Pallets[i] = o.R.Pallets[ln-1]
			}
			o.R.Pallets = o.R.Pallets[:ln-1]
			break
		}
	}

	return nil
}

// Containers retrieves all the records using an executor.
func Containers(mods ...qm.QueryMod) containerQuery {
	mods = append(mods, qm.From("\"containers\""))
	return containerQuery{NewQuery(mods...)}
}

// FindContainer retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindContainer(exec boil.Executor, iD string, selectCols ...string) (*Container, error) {
	containerObj := &Container{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"containers\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(nil, exec, containerObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "db: unable to select from containers")
	}

	return containerObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Container) Insert(exec boil.Executor, columns boil.Columns) error {
	if o == nil {
		return errors.New("db: no containers provided for insertion")
	}

	var err error
	currTime := time.Now().In(boil.GetLocation())

	if o.UpdatedAt.IsZero() {
		o.UpdatedAt = currTime
	}
	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(containerColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	containerInsertCacheMut.RLock()
	cache, cached := containerInsertCache[key]
	containerInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			containerAllColumns,
			containerColumnsWithDefault,
			containerColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(containerType, containerMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(containerType, containerMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"containers\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"containers\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "db: unable to insert into containers")
	}

	if !cached {
		containerInsertCacheMut.Lock()
		containerInsertCache[key] = cache
		containerInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// Update uses an executor to update the Container.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Container) Update(exec boil.Executor, columns boil.Columns) (int64, error) {
	currTime := time.Now().In(boil.GetLocation())

	o.UpdatedAt = currTime

	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	containerUpdateCacheMut.RLock()
	cache, cached := containerUpdateCache[key]
	containerUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			containerAllColumns,
			containerPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("db: unable to update containers, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"containers\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, containerPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(containerType, containerMapping, append(wl, containerPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	var result sql.Result
	result, err = exec.Exec(cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to update containers row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to get rows affected by update for containers")
	}

	if !cached {
		containerUpdateCacheMut.Lock()
		containerUpdateCache[key] = cache
		containerUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(exec)
}

// UpdateAll updates all rows with the specified column values.
func (q containerQuery) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to update all for containers")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to retrieve rows affected for containers")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ContainerSlice) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("db: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), containerPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"containers\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, containerPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to update all in container slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to retrieve rows affected all in update all container")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Container) Upsert(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("db: no containers provided for upsert")
	}
	currTime := time.Now().In(boil.GetLocation())

	o.UpdatedAt = currTime
	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(containerColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	containerUpsertCacheMut.RLock()
	cache, cached := containerUpsertCache[key]
	containerUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			containerAllColumns,
			containerColumnsWithDefault,
			containerColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			containerAllColumns,
			containerPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("db: unable to upsert containers, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(containerPrimaryKeyColumns))
			copy(conflict, containerPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"containers\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(containerType, containerMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(containerType, containerMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "db: unable to upsert containers")
	}

	if !cached {
		containerUpsertCacheMut.Lock()
		containerUpsertCache[key] = cache
		containerUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// Delete deletes a single Container record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Container) Delete(exec boil.Executor) (int64, error) {
	if o == nil {
		return 0, errors.New("db: no Container provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), containerPrimaryKeyMapping)
	sql := "DELETE FROM \"containers\" WHERE \"id\"=$1"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to delete from containers")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to get rows affected by delete for containers")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q containerQuery) DeleteAll(exec boil.Executor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("db: no containerQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to delete all from containers")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to get rows affected by deleteall for containers")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ContainerSlice) DeleteAll(exec boil.Executor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(containerBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), containerPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"containers\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, containerPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to delete all from container slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to get rows affected by deleteall for containers")
	}

	if len(containerAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Container) Reload(exec boil.Executor) error {
	ret, err := FindContainer(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ContainerSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ContainerSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), containerPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"containers\".* FROM \"containers\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, containerPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(nil, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "db: unable to reload all in ContainerSlice")
	}

	*o = slice

	return nil
}

// ContainerExists checks if the Container row exists.
func ContainerExists(exec boil.Executor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"containers\" where \"id\"=$1 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, iD)
	}
	row := exec.QueryRow(sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "db: unable to check if containers exists")
	}

	return exists, nil
}
